name: Publitics
favicon: null
layout_spectrum: 0.21631
typography_spectrum: 0.7666
title: 'PubliticsPR+Digital '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00aeef'
    - '#000000'
    - '#00ffff'
    - '#ffffff'
    - '#808080'
  brandStrength: 0.5
  lightness: 0.7131969819311053
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
